const crates = [
  {
    name: "Toothpick",
    toys: 8,
    common: 100,
    uncommon: 0,
    rare: 0,
    epic: 0,
    legendary: 0,
    mythical: 0,
    cost: 0.04,
    bestFor: "Common",
    image: "images/crates/toothpick.png",
  },
  {
    name: "Styrofoam",
    toys: 10,
    common: 80,
    uncommon: 20,
    rare: 0,
    epic: 0,
    legendary: 0,
    mythical: 0,
    cost: 0.1,
    bestFor: null,
    image: "images/crates/styrofoam.png",
  },
  {
    name: "Newspaper",
    toys: 12,
    common: 53,
    uncommon: 47,
    rare: 0,
    epic: 0,
    legendary: 0,
    mythical: 0,
    cost: 0.2,
    bestFor: null,
    image: "images/crates/newspaper.png",
  },
  {
    name: "Cardboard",
    toys: 14,
    common: 24,
    uncommon: 75,
    rare: 1,
    epic: 0,
    legendary: 0,
    mythical: 0,
    cost: 0.35,
    bestFor: "Uncommon",
    image: "images/crates/cardboard.png",
  },
  {
    name: "Wooden",
    toys: 16,
    common: 23,
    uncommon: 72,
    rare: 5,
    epic: 0,
    legendary: 0,
    mythical: 0,
    cost: 0.5,
    bestFor: null,
    image: "images/crates/wooden.png",
  },
  {
    name: "Tinfoil",
    toys: 18,
    common: 22,
    uncommon: 66,
    rare: 12,
    epic: 0,
    legendary: 0,
    mythical: 0,
    cost: 0.75,
    bestFor: null,
    image: "images/crates/tinfoil.png",
  },
  {
    name: "Rubber",
    toys: 20,
    common: 19,
    uncommon: 57,
    rare: 24,
    epic: 0,
    legendary: 0,
    mythical: 0,
    cost: 1.2,
    bestFor: null,
    image: "images/crates/rubber.png",
  },
  {
    name: "Acrylic",
    toys: 22,
    common: 14,
    uncommon: 43,
    rare: 43,
    epic: 0,
    legendary: 0,
    mythical: 0,
    cost: 2,
    bestFor: null,
    image: "images/crates/acrylic.png",
  },
  {
    name: "Ice",
    toys: 24,
    common: 8,
    uncommon: 27,
    rare: 65,
    epic: 0,
    legendary: 0,
    mythical: 0,
    cost: 3,
    bestFor: "Rare",
    image: "images/crates/ice.png",
  },
  {
    name: "Plastic",
    toys: 26,
    common: 7,
    uncommon: 21,
    rare: 66,
    epic: 6,
    legendary: 0,
    mythical: 0,
    cost: 5,
    bestFor: null,
    image: "images/crates/plastic.png",
  },
  {
    name: "Glass",
    toys: 28,
    common: 6,
    uncommon: 19,
    rare: 60,
    epic: 15,
    legendary: 0,
    mythical: 0,
    cost: 8,
    bestFor: null,
    image: "images/crates/glass.png",
  },
  {
    name: "Aluminum",
    toys: 30,
    common: 5,
    uncommon: 16,
    rare: 51,
    epic: 28,
    legendary: 0,
    mythical: 0,
    cost: 12.5,
    bestFor: null,
    image: "images/crates/aluminum.png",
  },
  {
    name: "Obsidian",
    toys: 32,
    common: 4,
    uncommon: 12,
    rare: 36,
    epic: 48,
    legendary: 0,
    mythical: 0,
    cost: 20,
    bestFor: "Epic",
    image: "images/crates/obsidian.png",
  },
  {
    name: "Metal",
    toys: 34,
    common: 2,
    uncommon: 7,
    rare: 22,
    epic: 67,
    legendary: 2,
    mythical: 0,
    cost: 32,
    bestFor: null,
    image: "images/crates/metal.png",
  },
  {
    name: "Titanium",
    toys: 36,
    common: 2,
    uncommon: 7,
    rare: 21,
    epic: 62,
    legendary: 8,
    mythical: 0,
    cost: 50,
    bestFor: null,
    image: "images/crates/titanium.png",
  },
  {
    name: "Gold",
    toys: 38,
    common: 2,
    uncommon: 6,
    rare: 18,
    epic: 56,
    legendary: 18,
    mythical: 0,
    cost: 80,
    bestFor: null,
    image: "images/crates/gold.png",
  },
  {
    name: "Kevlar",
    toys: 40,
    common: 1,
    uncommon: 5,
    rare: 15,
    epic: 47,
    legendary: 32,
    mythical: 0,
    cost: 125,
    bestFor: "Legendary",
    image: "images/crates/kevlar.png",
  },
  {
    name: "Carbon Fiber",
    toys: 42,
    common: 1,
    uncommon: 4,
    rare: 14,
    epic: 41,
    legendary: 38,
    mythical: 2,
    cost: 200,
    bestFor: null,
    image: "images/crates/carbon_fiber.png",
  },
  {
    name: "Error",
    toys: 44,
    common: 1,
    uncommon: 4,
    rare: 12,
    epic: 38,
    legendary: 40,
    mythical: 5,
    cost: 300,
    bestFor: null,
    image: "images/crates/error.png",
  },
  {
    name: "Luxurious",
    toys: 46,
    common: 0,
    uncommon: 3,
    rare: 9,
    epic: 26,
    legendary: 52,
    mythical: 10,
    cost: 500,
    bestFor: "Mythical",
    image: "images/crates/luxurious.png",
  },
];
const itemDatabase = [
  {
    name: "Titanium Block",
    category: "block",
    rarity: "Legendary",
    rate: 0.228675,
    image: "images/items/titanium_block.png",
    stats: {
      health: 1650,
    },
  },
  {
    name: "Shield Generator",
    category: "soldier",
    rarity: "Mythical",
    rate: 0.0014,
    image: "images/items/shield_generator.png",
    stats: {
      health: 100000,
      shield: 1000000,
    },
  },
  {
    name: "Orbital Laser Station",
    category: "soldier",
    rarity: "Mythical",
    rate: 0.001,
    image: "images/items/orbital_laser_station.png",
  },
  {
    name: "Laser Machinegunner",
    category: "soldier",
    rarity: "Mythical",
    rate: 0.0106,
    image: "images/items/laser_machinegunner.png",
    stats: {
      health: 10000,
      damage: 125,
      reload_time: 0.08,
      range: 50,
    },
  },
  {
    name: "Orbital Tech",
    category: "soldier",
    rarity: "Mythical",
    rate: 0.0106,
    image: "images/items/orbital_tech.png",
    stats: {
      health: 7500,
      damage: 4200,
      aoe: 7,
      reload_time: 4,
      range: 70,
    },
  },
  {
    name: "Railgunner",
    category: "soldier",
    rarity: "Mythical",
    rate: 0.0106,
    image: "images/items/railgunner.png",
    stats: {
      health: 5000,
      damage: 5200,
      reload_time: 5,
      range: 100,
    },
  },
  {
    name: "Plasma Mine",
    category: "trap",
    rarity: "Mythical",
    rate: 0.0518,
    image: "images/items/plasma_mine.png",
  },
  {
    name: "Plasma Spikes",
    category: "trap",
    rarity: "Mythical",
    rate: 0.0518,
    image: "images/items/plasma_spikes.png",
    stats: {
      damage: 5400,
    },
  },
  {
    name: "Void Outline Block",
    category: "block",
    rarity: "Mythical",
    rate: 0.0632,
    image: "images/items/void_outline_block.png",
    stats: {
      health: 25000,
    },
  },
  {
    name: "Subspace Block",
    category: "block",
    rarity: "Mythical",
    rate: 0.0772,
    image: "images/items/subspace_block.png",
    stats: {
      health: 20500,
    },
  },
  {
    name: "Luxurious Block",
    category: "block",
    rarity: "Mythical",
    rate: 0.093,
    image: "images/items/luxurious_block.png",
    stats: {
      health: 17000,
    },
  },
  {
    name: "Money Roll Block",
    category: "block",
    rarity: "Mythical",
    rate: 0.113,
    image: "images/items/money_roll_block.png",
    stats: {
      health: 14000,
    },
  },
  {
    name: "Error Block",
    category: "block",
    rarity: "Mythical",
    rate: 0.1376,
    image: "images/items/error_block.png",
    stats: {
      health: 11500,
    },
  },
  {
    name: "Barrier Block",
    category: "block",
    rarity: "Mythical",
    rate: 0.17,
    image: "images/items/barrier_block.png",
    stats: {
      health: 9300,
    },
  },
  {
    name: "Forcefield Block",
    category: "block",
    rarity: "Mythical",
    rate: 0.208,
    image: "images/items/forcefield_block.png",
    stats: {
      health: 7600,
    },
  },
  {
    name: "Howitzer",
    category: "soldier",
    rarity: "Legendary",
    rate: 0.0012,
    image: "images/items/howitzer.png",
    stats: {
      health: 12000,
      damage: 5000,
      aoe: 12,
      reload_time: 6,
      range: 135,
    },
  },
  {
    name: "Multi Rocketeer",
    category: "soldier",
    rarity: "Legendary",
    rate: 0.00965,
    image: "images/items/multi_rocketeer.png",
    stats: {
      health: 3000,
      damage: 230,
      aoe: 9,
      reload_time: 1,
      range: 40,
    },
  },
  {
    name: "Minigunner",
    category: "soldier",
    rarity: "Legendary",
    rate: 0.00965,
    image: "images/items/minigunner.png",
    stats: {
      health: 2000,
      damage: 32,
      reload_time: 0.1,
      range: 45,
    },
  },
  {
    name: "Heavy Sniper",
    category: "soldier",
    rarity: "Legendary",
    rate: 0.00965,
    image: "images/items/heavy_sniper.png",
    stats: {
      health: 1200,
      damage: 850,
      reload_time: 4,
      range: 90,
    },
  },
  {
    name: "Commander",
    category: "soldier",
    rarity: "Legendary",
    rate: 0.001075,
    image: "images/items/commander.png",
    stats: {
      health: 1000,
      damage: 165,
      reload_time: 0.8,
      range: 40,
      damage_buff: 15,
    },
  },
  {
    name: "Missile Silo",
    category: "trap",
    rarity: "Legendary",
    rate: 0.00375,
    image: "images/items/missile_silo.png",
    stats: {
      damage: 2150,
      aoe: 14,
      range: 135,
    },
  },
  {
    name: "TNT",
    category: "trap",
    rarity: "Legendary",
    rate: 0.03,
    image: "images/items/tnt.png",
    stats: {
      health: 2500,
      damage: 700,
      aoe: 11,
    },
  },
  {
    name: "Landmines",
    category: "trap",
    rarity: "Legendary",
    rate: 0.03,
    image: "images/items/landmines.png",
    stats: {
      damage: 850,
      aoe: 11,
    },
  },
  {
    name: "Metal Spikes",
    category: "trap",
    rarity: "Legendary",
    rate: 0.03,
    image: "images/items/metal_spikes.png",
    stats: {
      damage: 1100,
    },
  },
  {
    name: "Piggy Bank",
    category: "block",
    rarity: "Legendary",
    rate: 0.09375,
    image: "images/items/piggy_bank.png",
    stats: {
      health: 4000,
    },
  },
  {
    name: "Carbon Fiber Block",
    category: "block",
    rarity: "Legendary",
    rate: 0.060375,
    image: "images/items/carbon_fiber_block.png",
    stats: {
      health: 6250,
    },
  },
  {
    name: "Kevlar Block",
    category: "block",
    rarity: "Legendary",
    rate: 0.0786,
    image: "images/items/kevlar_block.png",
    stats: {
      health: 4800,
    },
  },
  {
    name: "Ballistic Glass Block",
    category: "block",
    rarity: "Legendary",
    rate: 0.103375,
    image: "images/items/ballistic_glass_block.png",
    stats: {
      health: 3650,
    },
  },
  {
    name: "Gold Block",
    category: "block",
    rarity: "Legendary",
    rate: 0.13475,
    image: "images/items/gold_block.png",
    stats: {
      health: 2800,
    },
  },
  {
    name: "Cookie Block",
    category: "block",
    rarity: "Legendary",
    rate: 0.1755,
    image: "images/items/cookie_block.png",
    stats: {
      health: 2150,
    },
  },
  {
    name: "Field Gun",
    category: "soldier",
    rarity: "Epic",
    rate: 0.001211,
    image: "images/items/field_gun.png",
  },
  {
    name: "Flamethrower",
    category: "soldier",
    rarity: "Epic",
    rate: 0.007211,
    image: "images/items/flamethrower.png",
    stats: {
      health: 1000,
      damage: 10,
      aoe: 6,
      reload_time: 0.18,
      range: 33,
    },
  },
  {
    name: "Tuber",
    category: "soldier",
    rarity: "Epic",
    rate: 0.007211,
    image: "images/items/tuber.png",
    stats: {
      health: 900,
      damage: 190,
      aoe: 8,
      reload_time: 4,
      range: 35,
    },
  },
  {
    name: "Machine Gunner",
    category: "soldier",
    rarity: "Epic",
    rate: 0.007211,
    image: "images/items/machine_gunner.png",
    stats: {
      health: 650,
      damage: 10,
      reload_time: 0.16,
      range: 40,
    },
  },
  {
    name: "Sniper",
    category: "soldier",
    rarity: "Epic",
    rate: 0.007211,
    image: "images/items/sniper.png",
    stats: {
      health: 400,
      damage: 150,
      reload_time: 3.5,
      range: 80,
    },
  },
  {
    name: "Officer",
    category: "soldier",
    rarity: "Epic",
    rate: 0.001211,
    image: "images/items/officer.png",
    stats: {
      health: 250,
      damage: 42,
      reload_time: 1,
      range: 35,
      range_buff: 15,
    },
  },
  {
    name: "Battery",
    category: "trap",
    rarity: "Epic",
    rate: 0.046868,
    image: "images/items/battery.png",
    stats: {
      health: 500,
      damage: 150,
      aoe: 10,
    },
  },
  {
    name: "Barbed Wire",
    category: "trap",
    rarity: "Epic",
    rate: 0.046868,
    image: "images/items/barbed_wire.png",
    stats: {
      damage: 230,
    },
  },
  {
    name: "Canned Block",
    category: "trap",
    rarity: "Epic",
    rate: 0.093763,
    image: "images/items/canned_block.png",
    stats: {
      health: 400,
    },
  },
  {
    name: "Magnet Block",
    category: "block",
    rarity: "Epic",
    rate: 0.050526,
    image: "images/items/magnet_block.png",
    stats: {
      health: 1250,
    },
  },
  {
    name: "Metal Block",
    category: "block",
    rarity: "Epic",
    rate: 0.063158,
    image: "images/items/metal_block.png",
    stats: {
      health: 1000,
    },
  },
  {
    name: "Tempered Glass Block",
    category: "block",
    rarity: "Epic",
    rate: 0.079921,
    image: "images/items/tempered_glass_block.png",
    stats: {
      health: 790,
    },
  },
  {
    name: "Outline Block",
    category: "block",
    rarity: "Epic",
    rate: 0.101026,
    image: "images/items/outline_block.png",
    stats: {
      health: 625,
    },
  },
  {
    name: "Obsidian Block",
    category: "block",
    rarity: "Epic",
    rate: 0.126289,
    image: "images/items/obsidian_block.png",
    stats: {
      health: 500,
    },
  },
  {
    name: "Scrap Metal Block",
    category: "block",
    rarity: "Epic",
    rate: 0.159868,
    image: "images/items/scrap_metal_block.png",
    stats: {
      health: 395,
    },
  },
  {
    name: "Rust Block",
    category: "block",
    rarity: "Epic",
    rate: 0.200474,
    image: "images/items/rust_block.png",
    stats: {
      health: 315,
    },
  },
  {
    name: "Mortar",
    category: "soldier",
    rarity: "Rare",
    rate: 0.00175,
    image: "images/items/mortar.png",
    stats: {
      health: 400,
      damage: 70,
      aoe: 10,
      reload_time: 4,
      range: 105,
    },
  },
  {
    name: "Automatic Shotgunner",
    category: "soldier",
    rarity: "Rare",
    rate: 0.007083,
    image: "images/items/automatic_shotgunner.png",
    stats: {
      health: 200,
      damage: 8,
      reload_time: 0.4,
      range: 25,
    },
  },
  {
    name: "Rocketeer",
    category: "soldier",
    rarity: "Rare",
    rate: 0.007083,
    image: "images/items/rocketeer.png",
    stats: {
      health: 160,
      damage: 40,
      aoe: 7,
      reload_time: 4,
      range: 30,
    },
  },
  {
    name: "Soldier",
    category: "soldier",
    rarity: "Rare",
    rate: 0.007083,
    image: "images/items/soldier.png",
    stats: {
      health: 120,
      damage: 3,
      reload_time: 0.24,
      range: 35,
    },
  },
  {
    name: "Marksman",
    category: "soldier",
    rarity: "Rare",
    rate: 0.007083,
    image: "images/items/marksman.png",
    stats: {
      health: 80,
      damage: 25,
      reload_time: 3,
      range: 70,
    },
  },
  {
    name: "Radio Operator",
    category: "soldier",
    rarity: "Rare",
    rate: 0.001167,
    image: "images/items/radio_operator.png",
    stats: {
      health: 50,
      range_buff: 10,
    },
  },
  {
    name: "Coin Mine",
    category: "trap",
    rarity: "Rare",
    rate: 0.046917,
    image: "images/items/coin_mine.png",
    stats: {
      damage: 40,
      aoe: 9,
    },
  },
  {
    name: "Thumbtacks",
    category: "trap",
    rarity: "Rare",
    rate: 0.046917,
    image: "images/items/thumbtacks.png",
    stats: {
      damage: 50,
    },
  },
  {
    name: "Boombox",
    category: "block",
    rarity: "Rare",
    rate: 0.01875,
    image: "images/items/boombox.png",
    stats: {
      health: 150,
    },
  },
  {
    name: "LED",
    category: "block",
    rarity: "Rare",
    rate: 0.028083,
    image: "images/items/led.png",
    stats: {
      health: 100,
    },
  },
  {
    name: "Pie Block",
    category: "block",
    rarity: "Rare",
    rate: 0.046917,
    image: "images/items/pie_block.png",
    stats: {
      health: 60,
    },
  },
  {
    name: "Metal Frame",
    category: "block",
    rarity: "Rare",
    rate: 0.03075,
    image: "images/items/metal_frame.png",
    stats: {
      health: 250,
    },
  },
  {
    name: "Aluminum Block",
    category: "block",
    rarity: "Rare",
    rate: 0.03575,
    image: "images/items/aluminum_block.png",
    stats: {
      health: 215,
    },
  },
  {
    name: "Brick Block",
    category: "block",
    rarity: "Rare",
    rate: 0.041583,
    image: "images/items/brick_block.png",
    stats: {
      health: 185,
    },
  },
  {
    name: "Stone Block",
    category: "block",
    rarity: "Rare",
    rate: 0.048083,
    image: "images/items/stone_block.png",
    stats: {
      health: 160,
    },
  },
  {
    name: "Glass Block",
    category: "block",
    rarity: "Rare",
    rate: 0.054917,
    image: "images/items/glass_block.png",
    stats: {
      health: 140,
    },
  },
  {
    name: "Rubik's Cube",
    category: "block",
    rarity: "Rare",
    rate: 0.064083,
    image: "images/items/rubik_s_cube.png",
    stats: {
      health: 120,
    },
  },
  {
    name: "Plastic Block",
    category: "block",
    rarity: "Rare",
    rate: 0.07325,
    image: "images/items/plastic_block.png",
    stats: {
      health: 105,
    },
  },
  {
    name: "Dice Block",
    category: "block",
    rarity: "Rare",
    rate: 0.085417,
    image: "images/items/dice_block.png",
    stats: {
      health: 90,
    },
  },
  {
    name: "Ice Block",
    category: "block",
    rarity: "Rare",
    rate: 0.098583,
    image: "images/items/ice_block.png",
    stats: {
      health: 78,
    },
  },
  {
    name: "Wood Log",
    category: "block",
    rarity: "Rare",
    rate: 0.1165,
    image: "images/items/wood_log.png",
    stats: {
      health: 66,
    },
  },
  {
    name: "Gravel Block",
    category: "block",
    rarity: "Rare",
    rate: 0.1325,
    image: "images/items/gravel_block.png",
    stats: {
      health: 58,
    },
  },
  {
    name: "Shotgunner",
    category: "soldier",
    rarity: "Uncommon",
    rate: 0.00775,
    image: "images/items/shotgunner.png",
    stats: {
      health: 40,
      damage: 6,
      reload_time: 1.5,
      range: 20,
    },
  },
  {
    name: "Demoman",
    category: "soldier",
    rarity: "Uncommon",
    rate: 0.00775,
    image: "images/items/demoman.png",
    stats: {
      health: 30,
      damage: 6,
      aoe: 6,
      reload_time: 3,
      range: 25,
    },
  },
  {
    name: "Specialist",
    category: "soldier",
    rarity: "Uncommon",
    rate: 0.00775,
    image: "images/items/specialist.png",
    stats: {
      health: 20,
      damage: 1,
      reload_time: 0.4,
      range: 30,
    },
  },
  {
    name: "Musketeer",
    category: "soldier",
    rarity: "Uncommon",
    rate: 0.00775,
    image: "images/items/musketeer.png",
    stats: {
      health: 10,
      damage: 12,
      reload_time: 7,
      range: 55,
    },
  },
  {
    name: "Gum",
    category: "trap",
    rarity: "Uncommon",
    rate: 0.047,
    image: "images/items/gum.png",
    stats: {
      slow_percent: 100,
      slow_duration: 5,
    },
  },
  {
    name: "Toy Caltrops",
    category: "trap",
    rarity: "Uncommon",
    rate: 0.047,
    image: "images/items/toy_caltrops.png",
    stats: {
      damage: 10,
    },
  },
  {
    name: "Sandbags",
    category: "block",
    rarity: "Uncommon",
    rate: 0.0275,
    image: "images/items/sandbags.png",
    stats: {
      health: 60,
    },
  },
  {
    name: "Burger Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.06625,
    image: "images/items/burger_block.png",
    stats: {
      health: 25,
    },
  },
  {
    name: "Wooden Planks",
    category: "block",
    rarity: "Uncommon",
    rate: 0.03125,
    image: "images/items/wooden_planks.png",
    stats: {
      health: 50,
    },
  },
  {
    name: "Acrylic Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.0365,
    image: "images/items/acrylic_block.png",
    stats: {
      health: 43,
    },
  },
  {
    name: "Rubber Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.04225,
    image: "images/items/rubber_block.png",
    stats: {
      health: 37,
    },
  },
  {
    name: "Tinfoil Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.049,
    image: "images/items/tinfoil_block.png",
    stats: {
      health: 32,
    },
  },
  {
    name: "Wooden Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.056,
    image: "images/items/wooden_block.png",
    stats: {
      health: 28,
    },
  },
  {
    name: "Jelly Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.06525,
    image: "images/items/jelly_block.png",
    stats: {
      health: 24,
    },
  },
  {
    name: "Dirt Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.0745,
    image: "images/items/dirt_block.png",
    stats: {
      health: 21,
    },
  },
  {
    name: "Puzzle Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.087,
    image: "images/items/puzzle_block.png",
    stats: {
      health: 18,
    },
  },
  {
    name: "Grass Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.09775,
    image: "images/items/grass_block.png",
    stats: {
      health: 16,
    },
  },
  {
    name: "Snow Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.11175,
    image: "images/items/snow_block.png",
    stats: {
      health: 14,
    },
  },
  {
    name: "Sand Block",
    category: "block",
    rarity: "Uncommon",
    rate: 0.1305,
    image: "images/items/sand_block.png",
    stats: {
      health: 12,
    },
  },
  {
    name: "Hunter",
    category: "soldier",
    rarity: "Common",
    rate: 0.008,
    image: "images/items/hunter.png",
    stats: {
      health: 9,
      damage: 1,
      reload_time: 1.25,
      range: 18,
    },
  },
  {
    name: "Grenadier",
    category: "soldier",
    rarity: "Common",
    rate: 0.008,
    image: "images/items/grenadier.png",
    stats: {
      health: 7,
      damage: 1,
      aoe: 5,
      reload_time: 2.5,
      range: 20,
    },
  },
  {
    name: "Recruit",
    category: "soldier",
    rarity: "Common",
    rate: 0.008,
    image: "images/items/recruit.png",
    stats: {
      health: 5,
      damage: 1,
      reload_time: 2,
      range: 25,
    },
  },
  {
    name: "Gunslinger",
    category: "soldier",
    rarity: "Common",
    rate: 0.008,
    image: "images/items/gunslinger.png",
    stats: {
      health: 3,
      damage: 2,
      reload_time: 4.5,
      range: 40,
    },
  },
  {
    name: "Bricks",
    category: "block",
    rarity: "Common",
    rate: 0.047,
    image: "images/items/bricks.png",
    stats: {
      damage: 2,
    },
  },
  {
    name: "Glue",
    category: "trap",
    rarity: "Common",
    rate: 0.047,
    image: "images/items/glue.png",
    stats: {
      slow_percent: 30,
      slow_duration: 20,
    },
  },
  {
    name: "Jenga Block",
    category: "block",
    rarity: "Common",
    rate: 0.094,
    image: "images/items/jenga_block.png",
    stats: {
      health: 10,
    },
  },
  {
    name: "Cardboard Box",
    category: "block",
    rarity: "Common",
    rate: 0.043,
    image: "images/items/cardboard_box.png",
    stats: {
      health: 10,
    },
  },
  {
    name: "Toothpick Block",
    category: "block",
    rarity: "Common",
    rate: 0.054,
    image: "images/items/toothpick_block.png",
    stats: {
      health: 8,
    },
  },
  {
    name: "Cheese Block",
    category: "block",
    rarity: "Common",
    rate: 0.061,
    image: "images/items/cheese_block.png",
    stats: {
      health: 7,
    },
  },
  {
    name: "Newspaper Block",
    category: "block",
    rarity: "Common",
    rate: 0.072,
    image: "images/items/newspaper_block.png",
    stats: {
      health: 6,
    },
  },
  {
    name: "Styrofoam Block",
    category: "block",
    rarity: "Common",
    rate: 0.086,
    image: "images/items/styrofoam_block.png",
    stats: {
      health: 5,
    },
  },
  {
    name: "Yarn Block",
    category: "block",
    rarity: "Common",
    rate: 0.107,
    image: "images/items/yarn_block.png",
    stats: {
      health: 4,
    },
  },
  {
    name: "Marshmallow Block",
    category: "block",
    rarity: "Common",
    rate: 0.143,
    image: "images/items/marshmallow_block.png",
    stats: {
      health: 3,
    },
  },
  {
    name: "Toothpick Frame",
    category: "block",
    rarity: "Common",
    rate: 0.215,
    image: "images/items/toothpick_frame.png",
    stats: {
      health: 2,
    },
  },
];
